TIME_FORMAT = '%Y.%m.%d-%H:%M:%S'
DEFAULTS = {
    "ignore": [
        "*node_modules*",
        "*venv*",
        "*__pycache__*",
        "**.env",
        "**package-lock.json",
        "**__pycache__**",
        "**migrations**",
        "**output**",
        "**.DS_Store",
        "**.git**",
        "**.gitignore**",
        "**dist**",
        "**build**",
        "**.mp4",
        "**.jpg",
        "**.png",
        "**.gif",
        "**.jpeg",
        "**.ico",
        "**tracer.json",
        "**context.txt",
    ],
    "interval": 1,
    "video_length": 60,
    "video_fps": 60,
    "gifs": False,
    "gif_resolutions": [
        {"name": "square", "dimensions": [2000, 2000]},
    ],
    "gif_length": 10,
    "gif_fps": 10,
    "group_by_file": False,
    "video": True,
    "video_resolutions": [
        {"name": "landscape", "dimensions": [4096, 2160]},
        {"name": "portrait", "dimensions": [2160, 4096]},
    ],
    "log_level": "INFO",
    "multi_processing": True,
    "session": "default",
    "render_sessions": ["default"],
    "all_sessions": ["default"],
    "openapi_key": "",
    "video_catch_phrase": "Howdy!",
    "sub_project": "main",
    "total_progress": "Just the beginning...",
}
